// Code generated by MockGen. DO NOT EDIT.
// Source: .\internal\interfaces\IAggregatedRepository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	sql "database/sql"
	reflect "reflect"

	helpers "github.com/GeuberLucas/Gofre/backend/pkg/helpers"
	models "github.com/GeuberLucas/Gofre/backend/services/reports/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIAggregatedRepository is a mock of IAggregatedRepository interface.
type MockIAggregatedRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAggregatedRepositoryMockRecorder
}

// MockIAggregatedRepositoryMockRecorder is the mock recorder for MockIAggregatedRepository.
type MockIAggregatedRepositoryMockRecorder struct {
	mock *MockIAggregatedRepository
}

// NewMockIAggregatedRepository creates a new mock instance.
func NewMockIAggregatedRepository(ctrl *gomock.Controller) *MockIAggregatedRepository {
	mock := &MockIAggregatedRepository{ctrl: ctrl}
	mock.recorder = &MockIAggregatedRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAggregatedRepository) EXPECT() *MockIAggregatedRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockIAggregatedRepository) GetAll(userId int) ([]models.Aggregated, helpers.ErrorType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", userId)
	ret0, _ := ret[0].([]models.Aggregated)
	ret1, _ := ret[1].(helpers.ErrorType)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockIAggregatedRepositoryMockRecorder) GetAll(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockIAggregatedRepository)(nil).GetAll), userId)
}

// GetByMonthAndYear mocks base method.
func (m *MockIAggregatedRepository) GetByMonthAndYear(userId, month, year int) (models.Aggregated, helpers.ErrorType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMonthAndYear", userId, month, year)
	ret0, _ := ret[0].(models.Aggregated)
	ret1, _ := ret[1].(helpers.ErrorType)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByMonthAndYear indicates an expected call of GetByMonthAndYear.
func (mr *MockIAggregatedRepositoryMockRecorder) GetByMonthAndYear(userId, month, year interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMonthAndYear", reflect.TypeOf((*MockIAggregatedRepository)(nil).GetByMonthAndYear), userId, month, year)
}

// GetByYear mocks base method.
func (m *MockIAggregatedRepository) GetByYear(userId, year int) ([]models.Aggregated, helpers.ErrorType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByYear", userId, year)
	ret0, _ := ret[0].([]models.Aggregated)
	ret1, _ := ret[1].(helpers.ErrorType)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByYear indicates an expected call of GetByYear.
func (mr *MockIAggregatedRepositoryMockRecorder) GetByYear(userId, year interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByYear", reflect.TypeOf((*MockIAggregatedRepository)(nil).GetByYear), userId, year)
}

// InsertOrUpdate mocks base method.
func (m *MockIAggregatedRepository) InsertOrUpdate(tx *sql.Tx, model *models.Aggregated) (helpers.ErrorType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOrUpdate", tx, model)
	ret0, _ := ret[0].(helpers.ErrorType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertOrUpdate indicates an expected call of InsertOrUpdate.
func (mr *MockIAggregatedRepositoryMockRecorder) InsertOrUpdate(tx, model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrUpdate", reflect.TypeOf((*MockIAggregatedRepository)(nil).InsertOrUpdate), tx, model)
}
