export enum CategoryExpenseEnum {
  "Mercado geral",
  "Delivery",
  "Restaurante e bares",
  "Vestuário",
  "Moradia",
  "Utilidades",
  "Decoração",
  "Educação",
  "Dependentes",
  "Saúde",
  "Entretenimento",
  "Serviços",
  "Impostos",
  "Transporte",
  "Presentes",
  "Pets",
  "Viagens",
  "Doações",
  "Apostas",
  "Livre",
  "Outros",
}
