export enum CategoryExpenseEnum {
  MERCADO_GERAL = "Mercado geral",
  DELIVERY = "Delivery",
  RESTAURANTE_E_BARES = "Restaurante e bares",
  VESTUARIO = "Vestuário",
  MORADIA = "Moradia",
  UTILIDADES = "Utilidades",
  DECORACAO = "Decoração",
  EDUCACAO = "Educação",
  DEPENDENTES = "Dependentes",
  SAUDE = "Saúde",
  ENTRETENIMENTO = "Entretenimento",
  SERVICOS = "Serviços",
  IMPOSTOS = "Impostos",
  TRANSPORTE = "Transporte",
  PRESENTES = "Presentes",
  PETS = "Pets",
  VIAGENS = "Viagens",
  DOACOES = "Doações",
  APOSTAS = "Apostas",
  LIVRE = "Livre",
  OUTROS = "Outros",
}
